name: AntiPluginLookUp
version: ${project.version}
main: me.entity303.antipluginlookup.main.AntiPluginLookUp
authors: [Entity303]
softdepend: [ProtocolLib]
commands:
 antipluginlookup:
  aliases: [aplu]
